runtime: python39  # Replace with your desired Python runtime version

entrypoint: gunicorn -b :$PORT main:app  # Modify as needed

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65

env_variables:
  FLASK_ENV: production

handlers:
- url: /.*
  script: auto